fanyi/fanyi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('practice/', include('practice.urls')),
    path('admin/', admin.site.urls),
]

fanyi/practice/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'practice'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('transcript/<int:transcript_pk>', views.TranscriptView.as_view(), name='transcript'),
    path('entry/<int:entry_pk>', views.entry, name='entry'),
    path('entry/<int:entry_pk>/vocab/<int:pk>/add', views.AddVocabView.as_view(), name='vocab_add'),
    path('entry/<int:entry_pk>/vocab/<int:pk>/remove', views.RemoveVocabView.as_view(), name='vocab_remove'),
    path('vocab/<int:pk>', views.UpdateVocabView.as_view(), name='vocab_edit'),
    path('login/', auth_views.LoginView.as_view(template_name='practice/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='practice/logout.html'), name='logout'),
]

fanyi/practice/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

class Transcript(models.Model):
    title = models.CharField(max_length=256)
    author = models.CharField(max_length=256, null=True)
    url = models.CharField(max_length=2048, null=True)
    date_published = models.DateField(null=True)
    date_added = models.DateField(auto_now_add=True)
    last_viewed = models.DateTimeField(null=True)

    def __str__(self):
        return self.title

class Entry(models.Model):
    class Difficulty(models.IntegerChoices):
        NONE = 0, _('-')
        EASY = 1, _('Easy')
        MEDIUM = 2, _('Medium')
        HARD = 3, _('Hard')

    transcript = models.ForeignKey(Transcript, on_delete=models.CASCADE)
    index = models.IntegerField()
    start_ms = models.IntegerField('start (ms)', null=True)
    end_ms = models.IntegerField('end (ms)', null=True)
    text_en = models.TextField('text (english)')
    notes = models.TextField('notes', null=True, blank=True)
    difficulty = models.IntegerField(choices=Difficulty.choices, default=Difficulty.NONE)

    class Meta:
        ordering = ['index']

    def __str__(self):
        s = self.text_en[:60]
        if len(self.text_en) > 60:
            s += '...'
        return s

class Translation(models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    index = models.IntegerField()
    source = models.CharField(max_length=256)
    text_cn_traditional = models.TextField('text (traditional)')
    text_cn_simplified = models.TextField('text (simplified)', null=True)
    text_cn_pinyin = models.TextField('text (pinyin)')

    class Meta:
        ordering = ['index']

class Vocab(models.Model):
    phrase = models.TextField()
    translation = models.TextField()
    time_created = models.DateTimeField(auto_now_add=True)
    time_last_modified = models.DateTimeField(auto_now_add=True)
    entries = models.ManyToManyField(Entry)

    class Meta:
        ordering = ['-time_last_modified']

fanyi/practice/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Entry

class EntryEditForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['difficulty', 'notes']

class EntryVocabForm(forms.Form):
    phrase = forms.CharField(label='Phrase', max_length=1024, required=False)
    translation = forms.CharField(label='Translation', max_length=1024, required=False)

    def clean(self):
        data = super().clean()
        if not data.get('phrase'):
            raise ValidationError('phrase cannot be empty.')
        if not data.get('translation'):
            raise ValidationError('translation cannot be empty.')

fanyi/practice/views.py
from django.http import HttpResponseRedirect
from django.views import generic
from django.utils import timezone
from django.urls import reverse
from django.db import transaction
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404, render

import operator
from functools import reduce

from .models import Transcript, Entry, Vocab
from .forms import EntryEditForm, EntryVocabForm

class IndexView(generic.list.ListView):
    template_name = 'practice/index.html'
    model = Transcript
    paginate_by = 20

    def get_queryset(self):
        return Transcript.objects.annotate(entry_count=Count('entry')) \
            .annotate(note_count=Count('entry', filter=Q(entry__notes__isnull=False) & ~Q(entry__notes=''))) \
            .annotate(vocab_count=Count('entry__vocab'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recent'] = Transcript.objects.annotate(entry_count=Count('entry')) \
            .annotate(note_count=Count('entry', filter=Q(entry__notes__isnull=False) & ~Q(entry__notes=''))) \
            .annotate(vocab_count=Count('entry__vocab')) \
            .filter(last_viewed__isnull=False) \
            .order_by('-last_viewed')[:10]
        return context

class TranscriptView(generic.list.ListView):
    template_name = 'practice/transcript.html'
    model = Entry
    paginate_by = 20

    def get_queryset(self):
        qs = Entry.objects.filter(transcript=self.kwargs['transcript_pk'])

        if self._is_notes_only():
            qs = qs.filter(Q(notes__isnull=False) & ~Q(notes=''))

        min_difficulty = self._min_difficulty()
        if min_difficulty > 0:
            qs = qs.filter(Q(difficulty__gte=min_difficulty))
            
        return qs.prefetch_related('vocab_set') \
            .order_by('index') \
            .all() \
            .prefetch_related('translation_set')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        transcript = Transcript.objects.get(pk=self.kwargs['transcript_pk'])
        context['transcript'] = transcript
        context['transcript_next'] = Transcript.objects.only('pk') \
            .filter(pk__gt=self.kwargs['transcript_pk']) \
            .order_by('pk') \
            .first()
        context['transcript_prev'] = Transcript.objects.only('pk') \
            .filter(pk__lt=self.kwargs['transcript_pk']) \
            .order_by('-pk') \
            .first()

        context['notes_only'] = self._is_notes_only()
        context['notes_only_toggle'] = not context['notes_only']

        context['difficulties'] = Entry.Difficulty.choices
        context['min_difficulty'] = self._min_difficulty()

        context['last_viewed'] = transcript.last_viewed
        transcript.last_viewed = timezone.now()
        transcript.save()

        return context

    def _is_notes_only(self):
        return self.request.GET.get('notes_only', '').lower() in ('t', 'true')

    def _min_difficulty(self):
        return int(self.request.GET.get('min_difficulty', 0))

class UpdateVocabView(generic.edit.UpdateView):
    template_name = 'practice/vocab.html'
    model = Vocab
    fields = ['phrase', 'translation']

    def get_success_url(self):
        return self.request.GET.get('next', reverse('practice:index'))

class AddVocabView(generic.edit.UpdateView):
    model = Vocab
    fields = []

    @transaction.atomic
    def form_valid(self, form):
        entry = get_object_or_404(Entry, pk=self.kwargs['entry_pk'])
        vocab = get_object_or_404(Vocab, pk=self.kwargs['pk'])
        vocab.time_last_modified = timezone.now()
        vocab.entries.add(entry)
        vocab.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return self.request.GET.get('next', reverse('practice:index'))

class RemoveVocabView(generic.edit.UpdateView):
    model = Vocab
    fields = []

    def form_valid(self, form):
        entry = get_object_or_404(Entry, pk=self.kwargs['entry_pk'])
        vocab = get_object_or_404(Vocab, pk=self.kwargs['pk'])
        vocab.entries.remove(entry)
        vocab.save()

        # Garbage collect unattached entries.
        Vocab.objects.annotate(entry_count=Count('entries')).filter(entry_count=0).delete()

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return self.request.GET.get('next', reverse('practice:index'))

class SearchVocabView(generic.list.ListView):
    template_name = 'practice/vocab/search.html'
    model = Vocab
    paginate_by = 20

    def get_queryset(self):
        qs = Vocab.objects.annotate(entry_count=Count('entries')) \
            .filter(~Q(entries__pk__exact=self.kwargs['entry_pk']))
        query = self.request.GET.get('query', None)
        if query:
            qs = qs.filter(Q(phrase__icontains=query) | Q(translation__icontains=query))
        return qs

def entry(request, entry_pk):
    if request.method == 'GET':
        return entry_GET(request, entry_pk)
    elif request.method == 'POST' and request.POST['form'] == 'edit_form':
        return entry_POST_edit(request, entry_pk)
    elif request.method == 'POST' and request.POST['form'] == 'vocab_form':
        return entry_POST_vocab(request, entry_pk)
    else:
        raise NotImplementedError()

def entry_GET(request, entry_pk):
    entry = get_object_or_404(Entry, pk=entry_pk)
    edit_form = EntryEditForm(instance=entry)
    vocab_form = EntryVocabForm(initial=request.GET)
    context = {'vocab_form': vocab_form, 'edit_form': edit_form, 'entry': entry}

    qs = Vocab.objects.annotate(entry_count=Count('entries')) \
        .filter(~Q(entries__pk__exact=entry.pk))
    phrase = request.GET.get('phrase', '')
    translation = request.GET.get('translation', '')
    filters = []
    if phrase:
        filters.append(Q(phrase__icontains=phrase))
    if translation:
        filters.append(Q(translation__icontains=translation))
    if filters:
        qs = qs.filter(reduce(operator.or_, filters))
    context['matches'] = qs[:20]

    return render(request, 'practice/entry.html', context)

def entry_POST_edit(request, entry_pk):
    entry = get_object_or_404(Entry, pk=entry_pk)
    vocab_form = EntryVocabForm()
    edit_form = EntryEditForm(request.POST, instance=entry)
    context = {'vocab_form': vocab_form, 'edit_form': edit_form, 'entry': entry}

    if edit_form.is_valid():
        edit_form.save()
        return HttpResponseRedirect(request.GET.get('next', reverse('practice:index')))

    return render(request, 'practice/entry.html', context)

def entry_POST_vocab(request, entry_pk):
    entry = get_object_or_404(Entry, pk=entry_pk)
    vocab_form = EntryVocabForm(request.POST)
    edit_form = EntryEditForm(instance=entry)
    context = {'vocab_form': vocab_form, 'edit_form': edit_form, 'entry': entry}

    if vocab_form.is_valid():
        entry.vocab_set.create(
            phrase=vocab_form.cleaned_data['phrase'],
            translation=vocab_form.cleaned_data['translation'])
        return HttpResponseRedirect(request.GET.get('next', reverse('practice:index')))

    return render(request, 'practice/entry.html', context)

fanyi/practice/templates/practice/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>

    <!-- bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'practice/base.css' %}">

    {% block stylesheets %}{% endblock %}
</head>
<body>
    {% block body %}{% endblock %}

    <!-- bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    {% block javascript %}{% endblock %}
</body>
</html>

fanyi/practice/templates/practice/entry.html
{% extends "./base.html" %}

{% load format_millis %}
{% load humanize %}

{% block body %}
    <h1>Entry</h1>
    <form id="edit_form">
        {% csrf_token %}
        <input type="hidden" id="next" name="next" value="{{ request.GET.next }}">
        <input type="hidden" name="form" value="edit_form">
        <table>
            <tr>
                <td class="metadata-header">Index:</td>
                <td>{{ entry.index | add:"1" }}</td>
            </tr>
            <tr>
                <td class="metadata-header">Text:</td>
                <td>{{ entry.text_en }}</td>
            </tr>
            {% for translation in entry.translation_set.all %}
                <tr>
                    <td class="metadata-header">Translation {{ translation.index | add:"1" }}:</td>
                    <td>
                        <span class="text_cn">
                            {{ translation.text_cn_traditional }}
                        </span>
                        <span class="source">
                            ({{ translation.source | capfirst}})
                        </span>
                        <div class="text_pinyin">
                            {{ translation.text_cn_pinyin }}
                        </div>
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <td class="metadata-header">Difficulty:</td>
                <td>
                    {{ edit_form.difficulty.errors }}
                    {{ edit_form.difficulty }}
                </td>
            </tr>
            <tr>
                <td class="metadata-header">Notes:</td>
                <td>
                    {{ edit_form.notes.errors }}
                    {{ edit_form.notes }}
                </td>
            </tr>
        </table>
        <input class="btn btn-primary btn-sm" type="submit" formmethod="post" formaction="{% url 'practice:entry' entry.pk %}?next={{ request.GET.next | urlencode }}" value="Save">
        {% if request.GET.next %}
            <a class="btn btn-primary btn-sm" href="{{ request.GET.next }}">Cancel</a>
        {% endif %}
    </form>
    <h3>Vocab</h3>
    <form id="vocab_form">
        {% csrf_token %}
        <input type="hidden" id="next" name="next" value="{{ request.GET.next }}">
        <input type="hidden" name="form" value="vocab_form">
        <table>
            <tr>
                <th>Phrase</th>
                <th>Translation</th>
                <th>Last modified</th>
                <th>Created</th>
                <th></th>
            </tr>
            <tr>
                <td>
                    {{ vocab_form.phrase.errors }}
                    {{ vocab_form.phrase }}
                </td>
                <td>
                    {{ vocab_form.translation.errors }}
                    {{ vocab_form.translation }}
                </td>
                <td>N/A</td>
                <td>N/A</td>
                <td>
                    <input class="btn btn-primary btn-sm" id="search" type="submit" formmethod="get" value="Search">
                    <input class="btn btn-primary btn-sm" type="submit" formmethod="post" value="Create">
                </td>
            </tr>
            {% for vocab in entry.vocab_set.all %}
                <tr>
                    <td><span class="vocab-phrase">"{{ vocab.phrase }}":</span></td>
                    <td><span class="vocab-translation">{{ vocab.translation }}</span></td>
                    <td>{{ vocab.time_last_modified | naturaltime }}</td>
                    <td>{{ vocab.time_created | naturaltime }}</td>
                    <td>
                        <input class="btn btn-primary btn-sm" type="submit" formmethod="post" formaction="{% url 'practice:vocab_remove' entry.pk vocab.pk %}?next={{ request.get_full_path | urlencode }}" value="Remove">
                        <a class="btn btn-primary btn-sm" href="{% url 'practice:vocab_edit' vocab.pk %}?next={{ request.get_full_path | urlencode }}">Edit</a>
                    </td>
                </tr>
            {% endfor %}
            {% for vocab in matches %}
                <tr>
                    <td><span class="vocab-phrase">"{{ vocab.phrase }}":</span></td>
                    <td><span class="vocab-translation">{{ vocab.translation }}</span></td>
                    <td>{{ vocab.time_last_modified | naturaltime }}</td>
                    <td>{{ vocab.time_created | naturaltime }}</td>
                    <td>
                        <input class="btn btn-primary btn-sm" type="submit" formmethod="post" formaction="{% url 'practice:vocab_add' entry.pk vocab.pk %}?next={{ request.get_full_path | urlencode }}" value="Add">
                        <a class="btn btn-primary btn-sm" href="{% url 'practice:vocab_edit' vocab.pk %}?next={{ request.get_full_path | urlencode }}">Edit</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        {% for error in vocab_form.non_field_errors %}
            <div class="error">Error: {{ error | escape }}</div>
        {% endfor %}
    </form>
{% endblock %}

{% block javascript %}
    <script>
        $("#vocab_form").submit(function (event) {
            if (event.originalEvent.submitter.id === "search") {
                $(this).children("input[name='csrfmiddlewaretoken']").remove()
            }
        });
    </script>
{% endblock %}

fanyi/practice/templates/practice/index.html
{% extends "./base.html" %}

{% load humanize %}

{% block title %}Practice{% endblock %}

{% block body %}
    <h1>Transcripts</h1>
    <h2>Recent</h2>
    <table>
        <tr>
            <th>Last viewed</th>
            <th>Author</th>
            <th>Title</th>
            <th>Date published</th>
            <th>Entries</th>
            <th>Vocab</th>
            <th>Notes</th>
        </tr>
        {% for transcript in recent %}
            <tr>
                <td>
                    {{ transcript.last_viewed | naturaltime }}
                </td>
                <td>
                    {{ transcript.author }}
                </td>
                <td>
                    <a href="{% url 'practice:transcript' transcript.pk %}">{{ transcript.title }}</a>
                </td>
                <td>
                    {{ transcript.date_published }}
                </td>
                <td>
                    {{ transcript.entry_count }}
                </td>
                <td>
                    {{ transcript.vocab_count }}
                </td>
                <td>
                    {{ transcript.note_count }}
                </td>
            </tr>    
        {% endfor %}
    </table>
    <h2>All</h2>
    <table>
        <tr>
            <th>Last viewed</th>
            <th>Author</th>
            <th>Title</th>
            <th>Date published</th>
            <th>Entries</th>
            <th>Vocab</th>
            <th>Notes</th>
        </tr>
        {% for transcript in page_obj %}
            <tr>
                <td>
                    {{ transcript.last_viewed | naturaltime }}
                </td>
                <td>
                    {{ transcript.author }}
                </td>
                <td>
                    <a href="{% url 'practice:transcript' transcript.pk %}">{{ transcript.title }}</a>
                </td>
                <td>
                    {{ transcript.date_published }}
                </td>
                <td>
                    {{ transcript.entry_count }}
                </td>
                <td>
                    {{ transcript.vocab_count }}
                </td>
                <td>
                    {{ transcript.note_count }}
                </td>
            </tr>    
        {% endfor %}
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

fanyi/practice/templates/practice/login.html
{% extends "./base.html" %}

{% block body %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'practice:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input class="btn btn-primary" type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock %}

fanyi/practice/templates/practice/logout.html
Bye bye!

fanyi/practice/templates/practice/transcript.html
{% extends "./base.html" %}

{% load format_millis %}
{% load humanize %}

{% block title %}{{ transcript.title }}{% endblock %}

{% block body %}
    <h1>{{ transcript.title }}</h1>
    <div class="pagination">
        <span class="step-links">
            {% if transcript_prev %}
                <a href="{% url 'practice:transcript' transcript_prev.pk %}">&laquo; previous</a>
            {% endif %}
            <a href="{% url 'practice:index' %}">index</a>
            {% if transcript_next %}
                <a href="{% url 'practice:transcript' transcript_next.pk %}">next &raquo;</a>
            {% endif %}
        </span>
    </div>
    <table>
        <tr>
            <td class="metadata-header">Author:</td>
            <td>{{ transcript.author }}</td>
        </tr>
        <tr>
            <td class="metadata-header">URL:</td>
            <td><a href="{{ transcript.url }}">{{ transcript.url }}</td>
        </tr>
        <tr>
            <td class="metadata-header">Date published:</td>
            <td>{{ transcript.date_published }}</td>
        </tr>
        <tr>
            <td class="metadata-header">Last viewed:</td>
            <td>{{ last_viewed | naturaltime }}</td>
        </tr>
    </table>
    {% if page_obj %}
        <table>
            <tr>
                <th>Index</th>
                <th>Timestamp</th>
                <th>Text</th>
                <th>Vocab</th>
                <th>Difficulty</th>
                <th>Notes</th>
                <th></th>
            </tr>
            {% for entry in page_obj %}
                <tr>
                    <td>{{ entry.index | add:"1" }}</td>
                    <td>{{ entry.start_ms | format_millis }}</td>
                    <td>
                        <div id="heading-{{ entry.index }}">
                            <button class="text_en btn-link" data-toggle="collapse" data-target="#collapse-{{ entry.index }}" aria-expanded="false" aria-controls="collapse-{{ entry.index }}">
                                {{ entry.text_en }}
                            </button>
                        </div>
                        <div id="collapse-{{ entry.index }}" class="collapse" aria-labelledby="heading-{{ entry.index }}">
                            <table>
                                {% for translation in entry.translation_set.all %}
                                    <span class="text_cn">
                                        {{ translation.text_cn_traditional }}
                                    </span>
                                    <span class="source">
                                        ({{ translation.source | capfirst}})
                                    </span>
                                    <div class="text_pinyin">
                                        {{ translation.text_cn_pinyin }}
                                    </div>
                                {% endfor %}
                            </table>
                        </div>
                    </td>
                    <td>
                        {% if entry.vocab_set.all %}
                            {% for vocab in entry.vocab_set.all %}
                                <div>
                                    "<span class="vocab-phrase">{{ vocab.phrase }}</span>": <span class="vocab-translation">{{ vocab.translation }}</span>
                                </div>
                            {% endfor %}
                        {% else %}
                            -
                        {% endif %}
                    </td>
                    <td>{{ entry.get_difficulty_display | default:"-" }}</td>
                    <td>{{ entry.notes | default:"-" | linebreaksbr }}</td>
                    <td>
                        <a href="{% url 'practice:entry' entry.pk %}?next={{ request.get_full_path | urlencode }}">Edit</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <div class="empty-content">No matching entries.</div>
    {% endif %}
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

fanyi/practice/templates/practice/vocab.html
{% extends "./base.html" %}

{% block body %}
    <h1>Vocab</h1>
    <form method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td class="metadata-header">Phrase:</td>
                <td>
                    {{ form.phrase.errors }}
                    {{ form.phrase }}
                </td>
            </tr>
            <tr>
                <td class="metadata-header">Translation:</td>
                <td>
                    {{ form.translation.errors }}
                    {{ form.translation }}
                </td>
            </tr>
        </table>
        <input class="btn btn-primary btn-sm" type="submit" value="Save">
    </form>
{% endblock %}